Week 2 Servlet doGet function
KyaCarrington/software-product-sprint pull request #3
Opened 2021-03-04 21:17 UTC by KyaCarrington

Week 2 Step 1 doGet function that should open my website

2021-03-04 21:53 UTC, enriquejosepadilla requested changes

2021-03-04 21:53 UTC, enriquejosepadilla commented on portfolio/src/main/java/com/google/sps/servlets/newServlet.java
> +    response.getWriter().println("<h1>Hello world!</h1>");
technically the code and the docs from line 9 don't match. You aren't returning the page views, yet.

2021-03-06 18:35 UTC, KyaCarrington reviewed
I deleted those two lines because I think that's what my previous feedback was referring to

2021-03-06 18:35 UTC, KyaCarrington commented on portfolio/src/main/java/com/google/sps/servlets/newServlet.java
> +    response.getWriter().println("<h1>Hello world!</h1>");
I just copy and pasted the top half of the document from the example one and can delete that comment. Other than that does everything look okay?

2021-03-08 13:23 UTC, enriquejosepadilla approved these changes

2021-03-08 22:50 UTC, merged

2021-03-08 22:51 UTC, KyaCarrington reviewed
I'm trying to add a new script file to my website but I'm honestly very confused about what I'm supposed to be doing